[project]
name = "slack-off"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-python>=4.12.0.88",
    "pywinctl>=0.4.1",
    "supervision>=0.27.0",
    "ultralytics>=8.3.248",
]
